name: Unpublish or Deprecate NPM previews for PR
on:
  pull_request_target:
    types:
      - closed
  push:
    branches:
      - chore/npm-publish-demo
jobs:
  unpublish:
    name: Unpublish or Deprecate NPM previews for PR
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Unpublish
        run: |
          toUnpublish=()

          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_PUBLISH_TOKEN}}" > .npmrc

          #prNumber="${{github.event.number}}"
          prNumber="120"

          for pkgName in $(lerna ls --l --json|jq -r '.[].name')
          do
            npm dist-tag rm "${pkgName}" "pr-${prNumber}" || true

            for pkgVersion in $(npm view ${pkgName} --json|jq -r .versions|grep "\-pr.${prNumber}."|sed 's/,//'| sed 's/\"//g')
            do
              toUnpublish+=("${pkgName}@${pkgVersion}")
            done
          done

          echo  "List: ${toUnpublish[*]}"|sed 's/ /\n/g'

          for (( i=${#toUnpublish[@]}-1; i>=0; i-- ))
          do
            echo ""
            echo "*** deprecating: ${toUnpublish[i]}"
            npm deprecate --force "${toUnpublish[i]}" "Deprecated PR preview" || true
          done


          for (( i=${#toUnpublish[@]}-1; i>=0; i-- ))
          do
            echo ""
            echo "unpublishing: ${toUnpublish[i]}"
            npm unpublish --force "${toUnpublish[i]}" || true
          done
